### PR TITLE
Switch to flag validation.

### PR DESCRIPTION
**Pull request by dlorenc**

### CODE REVIEW

**Comment by bobcallaway** [comment]
I can't seem to get this to actually change the URL if it is valid:

```
bcallawa@Bobs-IBM-MBP rekor % ./cli logproof --rekor_server http://not_a_host:3001 --last-size 5
Root Hash: 2876f2d983c74d8ddb9e2f89a03befb89944883c2cdea2563b048779854eb864
Hashes: []
```

That should have failed but it still connected to `http://localhost:3000`

**Comment by lukehinds** [comment]
I am getting the same:

```
go run cmd/cli/main.go upload --rekor_server http://example.com:3001/ --public-key tests/test_public_key.key --signature tests/test_file.sig --artifact-url https://raw.githubusercontent.com/projectrekor/rekor/a9e622a40e27e778f6f7e5a1f8ea437afb671b6e/tests/test_file.txt 
2020-12-07T09:37:23.481Z	INFO	app/upload.go:87	Downloading artifact..
2020-12-07T09:37:23.600Z	INFO	app/upload.go:99	Uploading manifest to Rekor...
2020-12-07T09:37:23.600Z	FATAL	app/upload.go:113	Post "http://localhost:3000/api/v1/add": dial tcp [::1]:3000: connect: connection refused
```

I will dig around and see if I can spot it.

**Comment by dlorenc** [comment]
> I can't seem to get this to actually change the URL if it is valid:

Weird, it triggers the validation error if you use something completely invalid or empty but the actual value isn't getting used.

**Comment by dlorenc** [comment]
D'oh, I was missing a line...

**Review by bobcallaway — APPROVED** [review]

**Comment by bobcallaway** [comment]
merged in main in https://github.com/projectrekor/rekor/commit/93c94f39d717684154ac06276919bd623f9c792f, so closing this

**Pull request closed without merging**
