### PR TITLE
Mirror signed release images from GCR to GHCR as part of release

### LINKED ISSUE #681: Publish container images to Github container registry
**Description**

Its a little tricky finding Rekor images right now. They do existing in GCR but aren't easy to discover. Having published and signed container images in GHCR will allow for them to be used in the public good instance and also by independent operators instead of building from source.

**Why Github container registry?**

I think github makes the images more easily discoverable for independent operators than google container registry. I'll file a ticket to publish rekor images there to so they match if folks think this is the right approach

### PR DESCRIPTION
**Pull request by k4leung4**
Signed-off-by: Kenny Leung <kleung@chainguard.dev>

#### Summary

Copy signed released image from GCR to GHCR using cosign cli copy command.
This will ensure the signature will be the same between the two registry.

This keep consistent with Fulcio, https://github.com/sigstore/fulcio/issues/421, to publish to GCR and GHCR.

#### Ticket Link

Fixes #681 

#### Release Note

```release-note
Signed release images are mirrored to GHCR.
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
cool

**Review by asraa — APPROVED** [review]

**Comment by k4leung4** [comment]
changed ghcr prefix to ghcr.io/sigstore/rekor, so the final image paths will be
ghcr.io/sigstore/rekor/rekor-server
ghcr.io/sigstore/rekor/rekor-cli

**Comment by dlorenc** [comment]
Looks like this one is stuck on a conflict

**Comment by k4leung4** [comment]
Conflict resolved.

**Review by cpanato — APPROVED** [review]

**Pull request merged**
