### PR TITLE
remove URL fetch of keys/artifacts server-side

### PR DESCRIPTION
**Pull request by bobcallaway**
We originally added the ability for Rekor API callers to specify URLs to fetch public keys, artifacts, & signatures to simplify fetching larger objects rather than forcing clients to download them locally and upload them to Rekor for verification. 

Now that we have the `hashedRekord` type, this patch removes the ability for the Rekor server to fetch arbitrary URLs before making entries into the log, largely due to the risk of [SSRF](https://owasp.org/www-community/attacks/Server_Side_Request_Forgery).

Note that the option for `rekor-cli` to specify URLs on the command line remains, as the CLI tool will download the artifacts locally and then insert the relevant contents in the appropriate position within the payload submitted to the Rekor server. 

Signed-off-by: Bob Callaway <bob.callaway@gmail.com>

### CODE REVIEW

**Review by dlorenc — APPROVED** [review]

**Comment by dlorenc** [comment]
When and how do you want to roll this out?

**Comment by bobcallaway** [comment]
It depends on how many releases we have before we go 1.0; given that it does deprecate function, it would be good to announce it in the next release (perhaps just the sharding stuff) and then we have a follow-on release that addresses the API (i.e. move to gRPC) and this fix. 

Thoughts?

**Comment by dlorenc** [comment]
SGTM, so hold this until we cut the next release?

**Comment by bobcallaway** [comment]
yup, sounds like a plan.

@cpanato we should include a note in the next rekor release noting that the "server side remote fetching of resources will be removed in the next release" (feel free to re-word)

**Comment by bobcallaway** [comment]
https://github.com/sigstore/rekor/blob/12d1a47c7ac986932a2734cb855c642ac01ffde4/pkg/api/index.go also has another instance of this pattern we should remove.

**Comment by Hayden-IO** [comment]
Also there's options to read sig and public key for PGP using `http.Client` instead of `util.FileOrURLReadCloser`

https://github.com/sigstore/rekor/blob/5025a24e2861d1876d67a09cf6bfad0ee76d64c8/pkg/pki/pgp/pgp.go#L84

https://github.com/sigstore/rekor/blob/5025a24e2861d1876d67a09cf6bfad0ee76d64c8/pkg/pki/pgp/pgp.go#L225

**Comment by Hayden-IO** [comment]
Did we want to include something in 0.6 around the deprecation of this? 
@cpanato fyi

**Comment by bobcallaway** [comment]
it was in the changelog

**Comment by Hayden-IO** [comment]
Ah missed it, all good!

**Comment by dlorenc** [comment]
Should be safe to merge after that goes out!

**Pull request merged**
