### PR TITLE
Feature: add search support for sha512

### PR DESCRIPTION
**Pull request by kommendorkapten**
#### Summary

This commit introduces the possibility to *search* via sha512 digests. Example of how this could be useful is for the npm ecosystem. npm often relies on sha512 digests, and provenance attestations in intoto format may use sha512 digests as the subject. Subjects are extract during uploads and added as index keys, which are then stored in Redis. This feature lets the cli accept sha512 digests, and the server to accept them to use when searching in the Redis cache.

Signed-off-by: Fredrik Skogman <kommendorkapten@github.com>

#### Release Note
Rekor entries can now be searched by SHA512 digests (if they appear as subjects in an intoto attestation).

#### Documentation
Don't think so. The rekor cli help is updated for search.

### CODE REVIEW

**Comment by kommendorkapten** [comment]
Hm, I don't get any updates to the generated files when I'm running things locally. I'm using a mac, not Linux, but that shouldn't matter? The differences in the files are mostly on how the comments are formatted. 

```shell
$ ./hack/tools/bin/swagger generate client -f openapi.yaml -q -r COPYRIGHT.txt -t pkg/generated --additional-initialism=TUF
$ ./hack/tools/bin/swagger generate server -f openapi.yaml -q -r COPYRIGHT.txt -t pkg/generated --exclude-main -A rekor_server --flag-strategy=pflag --default-produces application/json --additional-initialism=TUF
$ git status
On branch feat_search_sha512
nothing to commit, working tree clean
``` 

```shell
$ touch openapi.yaml
$ make
/Users/kommendorkapten/git/rekor/hack/tools/bin/swagger validate openapi.yaml
2022/10/21 13:53:05
The swagger spec at "openapi.yaml" is valid against swagger specification 2.0
...
CGO_ENABLED=0 go build -trimpath -ldflags "-X sigs.k8s.io/release-utils/version.gitVersion=v0.12.0-67-g39562d2 -X sigs.k8s.io/release-utils/version.gitCommit=39562d2a3e3d0133e3aa3a042b2882d83432691a -X sigs.k8s.io/release-utils/version.gitTreeState="clean" -X sigs.k8s.io/release-utils/version.buildDate=2022-10-21T11:30:17Z" -o rekor-server ./cmd/rekor-server
$ git status
On branch feat_search_sha512
nothing to commit, working tree clean
```

**Comment by bobcallaway** [comment]
> Hm, I don't get any updates to the generated files when I'm running things locally. I'm using a mac, not Linux, but that shouldn't matter? The differences in the files are mostly on how the comments are formatted.
> 
> ```shell
> $ ./hack/tools/bin/swagger generate client -f openapi.yaml -q -r COPYRIGHT.txt -t pkg/generated --additional-initialism=TUF
> $ ./hack/tools/bin/swagger generate server -f openapi.yaml -q -r COPYRIGHT.txt -t pkg/generated --exclude-main -A rekor_server --flag-strategy=pflag --default-produces application/json --additional-initialism=TUF
> $ git status
> On branch feat_search_sha512
> nothing to commit, working tree clean
> ```
> 
> ```shell
> $ touch openapi.yaml
> $ make
> /Users/kommendorkapten/git/rekor/hack/tools/bin/swagger validate openapi.yaml
> 2022/10/21 13:53:05
> The swagger spec at "openapi.yaml" is valid against swagger specification 2.0
> ...
> CGO_ENABLED=0 go build -trimpath -ldflags "-X sigs.k8s.io/release-utils/version.gitVersion=v0.12.0-67-g39562d2 -X sigs.k8s.io/release-utils/version.gitCommit=39562d2a3e3d0133e3aa3a042b2882d83432691a -X sigs.k8s.io/release-utils/version.gitTreeState="clean" -X sigs.k8s.io/release-utils/version.buildDate=2022-10-21T11:30:17Z" -o rekor-server ./cmd/rekor-server
> $ git status
> On branch feat_search_sha512
> nothing to commit, working tree clean
> ```

try `make clean-gen` followed by `make`?

**Comment by kommendorkapten** [comment]
No :(

Same:
```shell
$ make clean-gen && make
rm -rf dist
rm -rf hack/tools/bin
rm -rf rekor-cli rekor-server
rm -f *fuzz.zip
rm -rf pkg/generated/client/entries/create_log_entry_parameters.go pkg/generated/client/entries/create_log_entry_responses.go pkg/generated/client/entries/entries_client.go pkg/generated/client/entries/get_log_entry_by_index_parameters.go pkg/generated/client/entries/get_log_entry_by_index_responses.go pkg/generated/client/entries/get_
...
CGO_ENABLED=0 go build -trimpath -ldflags "-X sigs.k8s.io/release-utils/version.gitVersion=v0.12.0-67-g39562d2 -X sigs.k8s.io/release-utils/version.gitCommit=39562d2a3e3d0133e3aa3a042b2882d83432691a -X sigs.k8s.io/release-utils/version.gitTreeState="clean" -X sigs.k8s.io/release-utils/version.buildDate=2022-10-21T11:30:17Z" -o rekor-server ./cmd/rekor-server
$ git status
On branch feat_search_sha512
nothing to commit, working tree clean
```

**Comment by kommendorkapten** [comment]
Booted a linux container (ubuntu) and ran the commands:

```shell
$ uname -a
Linux 0f0cec2ab8f3 5.10.104-linuxkit #1 SMP PREEMPT Wed Mar 9 19:01:25 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
$ go version
go version go1.18.1 linux/arm64
$ make clean-gen && make
rm -rf dist
rm -rf hack/tools/bin
rm -rf rekor-cli rekor-server
rm -f *fuzz.zip
...
$ git status
On branch feat_search_sha512
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   hack/tools/go.sum
```

So no changes to the generated files, only the go.sum for the tool. Will dig deeper into what version(s) the runner is using.

**Review by asraa — DISMISSED** [review]
Changes otherwise lgtm besides the swagger issues :/

You should be able to add a CLI test, since intoto attestations index sha512's if present similar to https://github.com/sigstore/rekor/blob/e41b4cb2bd14ef9c2ce4a1a533b05a06803c7927/tests/e2e_test.go#L813

**Comment by bobcallaway** [comment]
the builder is using go 1.19.2 vs your ubuntu container using 1.18.1. 

on my mac with go 1.19, when I do `make clean && make` i do get the changes shown in the CI test so I think its that.

**Comment by bobcallaway** [comment]
and +1 to @asraa 's comment about adding a cli test, otherwise code LGTM

**Comment by kommendorkapten** [comment]
Great find @bobcallaway, thanks. 
Yes, I'll add an cli test too as @asraa proposed!

**Comment by dlorenc** [comment]
Nice work!

**Review by asraa — APPROVED** [review]

**Review by bobcallaway — APPROVED** [review]

**Pull request merged**
