### PR TITLE
Implement /api/v1/version for rekor-server

### PR DESCRIPTION
**Pull request by Foxboron**
#### Summary
This implements `/api/v1/version` and allows us to properly check what version `rekor-server` is currently running on a deployed instance.

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by dlorenc** [comment]
Nice! Let's see if GitHub is working again...

**Comment by Foxboron** [comment]
The only discussion point I believe is if the different LDFLAGS values really belong under `pkg/api`, or if we want `pkg/version` to contain them?

**Comment by dlorenc** [comment]
> The only discussion point I believe is if the different LDFLAGS values really belong under `pkg/api`, or if we want `pkg/version` to contain them?

I don't mind much either way. The new `debug/buildinfo` stuff in go 1.18 will help out here in a few months when we can upgrade to it.

**Comment by Foxboron** [comment]
Fixed the missing license header. I can squash the commit with the generated swagger stuff if it's needed.

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
