### PR TITLE
Add back owners for rfc3161 package type

### PR DESCRIPTION
**Pull request by Hayden-IO**
Accidentally deleted in previous PR

Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by Hayden-IO** [comment]
Because @loosebazooka doesn't have write access to this repo, I need to remove him. Codeowners unfortunately isn't that useful, providing write access per path...

**Comment by asraa** [comment]
> 
Because @loosebazooka doesn't have write access to this repo, I need to remove him. Codeowners unfortunately isn't that useful, providing write access per path...


Doesn't it automatically alert/request review from them?

**Review by asraa — DISMISSED** [review]
LGTM, minus keeping @loosebazooka in for review transparency

**Comment by Hayden-IO** [comment]
I don't know if it still picks him - Do you?

**Comment by asraa** [comment]
Yeah they're automatically added for review on those paths, so I'd keep him in 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners

**Comment by Hayden-IO** [comment]
Reverted!

**Review by asraa — APPROVED** [review]

**Comment by loosebazooka** [comment]
image

**Pull request merged**
