### PR TITLE
Remove replace in go.mod

### LINKED ISSUE #1440: docs: rekor-cli `go install` directions broken
**Description**

The instructions at https://docs.sigstore.dev/rekor/installation/#using-go-install are out-of-date as `go install` is incompatible with the replace directive added in #1272

https://github.com/golang/go/issues/44840#issuecomment-792789581
```
go install -v github.com/sigstore/rekor/cmd/rekor-cli@latest
go: github.com/sigstore/rekor/cmd/rekor-cli@latest (in github.com/sigstore/rekor@v1.1.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**What should the correct behavior be?**

I would expect the documented installation options to work, or a note explaining the problem if it's expected to be temporary.

**Version**

N/A

### PR DESCRIPTION
**Pull request by Hayden-IO**
Fixes https://github.com/sigstore/rekor/issues/1440

### CODE REVIEW

**Comment by Hayden-IO** [comment]
cc @AdamKorcz - Is this going to break fuzzing?

**Comment by Hayden-IO** [comment]
Yep, definitely does. Can we upstream those fuzzing changes?

**Review by priyawadhwa — DISMISSED** [review]

**Comment by AdamKorcz** [comment]
> Yep, definitely does. Can we upstream those fuzzing changes?

I could fix it temporarily by doing this in the OSS-Fuzz build script instead, so we perform the replace when OSS-Fuzz builds the fuzzers. I can upstream these changes next week.

**Comment by Hayden-IO** [comment]
Thanks!

**Comment by Hayden-IO** [comment]
@AdamKorcz Any progress on upstreaming?

**Comment by Hayden-IO** [comment]
Bumping again - This is blocking a new release, so I may need to remove fuzzing temporarily.

**Comment by AdamKorcz** [comment]
Sorry @haydentherapper 
Could you place the same replace right after this line?
https://github.com/sigstore/rekor/blob/4eabf777378ac86d091c20547ca0f3de8e4534d8/tests/oss_fuzz.sh#L22

**Comment by AdamKorcz** [comment]
It should do the trick.

**Comment by Hayden-IO** [comment]
Will do! Thanks for the pointer.

**Comment by Hayden-IO** [comment]
@AdamKorcz I ended up switching out the dependency to your fork. Otherwise, I'd also need to tag some of the fuzz test files to not always build, and this seemed like an easier approach.

**Review by bobcallaway — APPROVED** [review]

**Review by cpanato — APPROVED** [review]

**Comment by AdamKorcz** [comment]
@haydentherapper Awesome, that works fine from the OSS-Fuzz side of things as well. Thanks!

**Pull request merged**
