### PR TITLE
rekor-cli: Pretty print for get cmd

### PR DESCRIPTION
**Pull request by ahmetb**
Otherwise prints []byte contents which are not quite usable.

### CODE REVIEW

**Comment by bobcallaway** [comment]
+1 on the []byte output not being usable... but I'm not a fan of exposing the internal struct names, etc to the CLI. 

would it be possible to change this to a type-specific marshaling method instead?

**Comment by ahmetb** [comment]
I think we should probably just marshal as json and pretty-print it out.

**Comment by dlorenc** [comment]
Ugh yeah this doesn't look great either:

```shell
Index: 500
IntegratedTime: 2021-02-24T13:41:46Z
UUID: 438e1c524bf60fee2b72a4349a8e0b74efdd1e8395989e260314324e3fe7106d
Body: (*rekord.V001Entry)(0xc00054a0f0)({
 RekordObj: (models.RekordV001Schema) {
  Data: (*models.RekordV001SchemaData)(0xc00052e600)({
   Content: (strfmt.Base64) ,
   Hash: (*models.RekordV001SchemaDataHash)(0xc0005475f0)({
    Algorithm: (*string)(0xc000547660)((len=6) "sha256"),
    Value: (*string)(0xc000547690)((len=64) "e45f27eb4546f85fcfe6d25b70a29906ef40dea845da8df8dd55ae6a08912b2d")
   }),
   URL: (strfmt.URI)
  }),
  ExtraData: (interface {}) <nil>,
  Signature: (*models.RekordV001SchemaSignature)(0xc0004d2140)({
   Content: (strfmt.Base64) (len=64 cap=64) lm90QmxFWwoNbRyW3/tBvk0jPhmMSmdhFRO7B6OoknZa7+tAZPkr7W03F/ahmqzg+OEeG7iFpOQoTCxWeMvbBw==,
   Format: (string) (len=4) "x509",
   PublicKey: (*models.RekordV001SchemaSignaturePublicKey)(0xc00052e660)({
    Content: (strfmt.Base64) (len=113 cap=113) LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQWxqMThENk9FQnpXbmhYaTFKZjIzdG5ldjRuRFZGZ0doZ29GWWlNMCtnU2s9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=,
    URL: (strfmt.URI)
   }),
   URL: (strfmt.URI)
  })
 },
 fetchedExternalEntities: (bool) false,
 keyObj: (pki.PublicKey) <nil>,
 sigObj: (pki.Signature) <nil>
})
```

I'll try out something, I think I know how to actually decode these now...

**Comment by ahmetb** [comment]
pushing a commit  5fd6568 from last week that does pretty-printing of JSON. let me know if that's good enough, or push more commits.

**Comment by dlorenc** [comment]
```
Index: 500
IntegratedTime: 2021-02-24T13:41:46Z
UUID: 438e1c524bf60fee2b72a4349a8e0b74efdd1e8395989e260314324e3fe7106d
Body: {
  "RekordObj": {
    "data": {
      "hash": {
        "algorithm": "sha256",
        "value": "e45f27eb4546f85fcfe6d25b70a29906ef40dea845da8df8dd55ae6a08912b2d"
      }
    },
    "signature": {
      "content": "lm90QmxFWwoNbRyW3/tBvk0jPhmMSmdhFRO7B6OoknZa7+tAZPkr7W03F/ahmqzg+OEeG7iFpOQoTCxWeMvbBw==",
      "format": "x509",
      "publicKey": {
        "content": "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQWxqMThENk9FQnpXbmhYaTFKZjIzdG5ldjRuRFZGZ0doZ29GWWlNMCtnU2s9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo="
      }
    }
  }
}
```

Perfect!!!

**Pull request merged**
