### PR TITLE
Add backfill-redis to the release artifacts

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- Add backfill-redis to the release artifacts
- add version information for backfill-redis

### CODE REVIEW

**Review by Hayden-IO — APPROVED** [review]
To confirm, this won't build artifacts for GH because we don't specify that in goreleaser, correct?

**Review by vaikas — APPROVED** [review]
Thanks for doing this!

**Comment by cpanato** [comment]
> To confirm, this won't build artifacts for GH because we don't specify that in goreleaser, correct?

Yes, it only build the image

**Review by priyawadhwa — APPROVED** [review]

**Comment by Hayden-IO** [comment]
@priyawadhwa Can we get this into the release too? And cherry pick in https://github.com/sigstore/rekor/pull/1163?

**Comment by priyawadhwa** [comment]
Sure! could you open a PR for the cherry-pick and I can approve it?

**Comment by cpanato** [comment]
@priyawadhwa @haydentherapper will cherry pick this

**Pull request merged**
