### PR TITLE
Handle possibly nil values gracefully

### PR DESCRIPTION
**Pull request by Hayden-IO**
When searching by entry, you could construct an entry without a required field, causing canonicalization to fail.

Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

### CODE REVIEW

**Review by asraa — COMMENTED** [review]
Could you explain the context of this? 

I'm guessing it's that you're running `Canonicalize` on a client before running a Search by entry query. Where are you getting the entry though that you are canonicalizing, and why doesn't it have the ContentHash/PayloadHash? These seem required... (or is this a backwards compatible thing, where a while ago these types somehow skipped that... i can't remember)

**Comment by Hayden-IO** [comment]
@bobcallaway @asraa PTAL

I would prefer to fix this by specifying two different schemas, one for input and one for a canonicalized output. This would allow us to set different required fields for each. This fix should be sufficient.

**Comment by Hayden-IO** [comment]
@AdamKorcz This is an interesting vector for fuzzing. I suspect there's more instances of this. Happy to chat offline about the details.

**Comment by asraa** [comment]
> I would prefer to fix this by specifying two different schemas, one for input and one for a canonicalized output. This would allow us to set different required fields for each. This fix should be sufficient.

I don't think we want a per-entry input schema, but rather an input schema that works across all types. Something like

ProposedEntry:
  * type: intoto
  * pk: pk
  * etc...

But it would be a breaking change :| so minimally let's fix it right now. I'll open up an issue which i'll flag as a v2 improvement

**Comment by Hayden-IO** [comment]
Moving to draft as @bobcallaway is fixing this in a better way. Will close once we have merged the fixes for 0.0.1/2

**Comment by Hayden-IO** [comment]
@bobcallaway Were you planning to add in the 0.0.2 changes too? Envelope is calculated server side, correct?

**Pull request closed without merging**
