### PR TITLE
Update checkpoint origin to match previous origin, make configurable

### PR DESCRIPTION
**Pull request by Hayden-IO**
Changing the origin breaks witnessing, so I've reverted this change, but made it configurable so we can change the value in staging.

Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

### CODE REVIEW

**Comment by Hayden-IO** [comment]
/HOLD

I am chatting with the Trillian team now to find out if we need to differentiate between shards.

**Comment by Hayden-IO** [comment]
unrelated e2e test failure

**Comment by dlorenc** [comment]
Is there any context on the breakage here? What broke without this change?

**Comment by Hayden-IO** [comment]
Sorry for lack of context. The omniwitness monitor that's run by Trust Fabric is configurable with the origin of the checkpoint - https://github.com/google/trillian-examples/blob/master/witness/golang/omniwitness/feeder_configs/rekor.yaml#L2

Verification requires a known origin value. Once we roll out 0.12 to prod, the witness will break.

**Comment by dlorenc** [comment]
It seems like that config should be updated, the correct name should probably be something closer to what v0.12.0 does right? This isn't meant to be a canonical "rekor" instance, we should at least prefix it with something like rekor.sigstore.dev.

**Comment by Hayden-IO** [comment]
I was planning to have different names for staging, like "Rekor Staging". Note that the hostname is already included in the checkpoint note alongside the public key too.

I have asked Trillian how we should handle sharding - should each shard be considered a unique origin? That would mean we'd need a new witness for each shard.

**Comment by Hayden-IO** [comment]
I see your point about not having this be the canonical rekor instance. I'll update this tomorrow after getting clarity on if the shard should be included.

**Comment by Hayden-IO** [comment]
The current checkpoint origin is ideal, and I'll update the configuration.

**Pull request closed without merging**
