### PR TITLE
api.SearchLogQueryHandler thread safety

### PR DESCRIPTION
**Pull request by cdris**
Signed-off-by: Ceridwen Driskill <cdriskill@google.com>

#### Summary

Updated to use channels instead of appending (which is not thread safe) in goroutines.

### CODE REVIEW

**Comment by cdris** [comment]
Fixes #997

**Review by bobcallaway — APPROVED** [review]

**Review by priyawadhwa — APPROVED** [review]

**Review by Bom123789 — CHANGES_REQUESTED** [review]
- `[]()****`

**Review by Bom123789 — CHANGES_REQUESTED** [review]
- `[]()****`

**Review by Bom123789 — CHANGES_REQUESTED** [review]
- `[]()****`

**Review by Bom123789 — CHANGES_REQUESTED** [review]
- `[]()****`

**Review by Bom123789 — APPROVED** [review]
- `[]()****`

**Pull request merged**
